from . import bf_cx_theme
from . import bf_cx_program
from . import bf_cx_wave
from . import bf_cx_feedback
from . import bf_cx_complaint
from . import bf_cx_testimonial
from . import survey_user_input
from . import rating_rating
from . import mail_thread
from . import res_partner
from . import res_config_settings
