from . import bf_phishing_template
from . import bf_phishing_campaign
from . import bf_phishing_result
from . import bf_security_profile
from . import bf_training_assignment
from . import bf_reported_phish
from . import bf_mail_connector
from . import bf_clawback
from . import bf_security_dashboard
from . import res_partner
