{
    "name": "Blue Fox — Operations Pack",
    "summary": "Unified inbox, meetings, contact intelligence, and chatter polish for consulting/MSP teams",
    "version": "18.0.1.0.0",
    "category": "Productivity",
    "license": "LGPL-3",
    "author": "Blue Fox Inc.",
    "website": "https://bluefoxconsultant.com",
    "depends": [
        "bf_email_management",
        "bf_meeting",
        "bf_persona",
        "bf_helpdesk",
        "bf_chatter_chronological",
        "bf_chatter_timesheet",
        "bf_mail_import",
        "bf_mail_subject_clean",
        "bf_mail_vigie",
        "bf_hour_bank",
    ],
    "data": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
