from . import knowledge_section
from . import knowledge_matrix
from . import knowledge_item
from . import project_project
from . import credential_type
from . import project_credential
from . import document_type
from . import document_software
from . import project_document
from . import document_version
from . import document_distribution
from . import res_partner
from . import knowledge_dashboard
from . import res_config_settings
from . import corporate_resolution
from . import corporate_director
from . import corporate_officer
from . import corporate_compliance
from . import raci_stakeholder
from . import project_task

# Corps documentaire (sections rédigées dans Odoo)
from . import res_company_brand
from . import document_section_type
from . import document_type_section
from . import document_section
from . import document_version_section
from . import project_document_body
from . import document_version_body
