from . import appointment_email_schedule
from . import appointment_intake
from . import calendar_event
from . import ir_mail_server
from . import mail_template
from . import onboarding_onboarding
from . import res_company
from . import res_config_settings
from . import resource_booking
from . import resource_booking_combination
from . import resource_booking_type
from . import resource_calendar
