from . import bf_note_tag
from . import bf_note_link_mixin
from . import bf_note_link
from . import bf_note
from . import bf_note_activity_wizard
from . import bf_note_task_wizard
from . import bf_note_reroute
from . import res_partner
from . import project_task
from . import project_project
from . import crm_lead
from . import res_users
from . import onboarding_onboarding
