from . import privacy_framework
from . import privacy_lawful_basis
from . import privacy_right
from . import privacy_framework_mixin
from . import res_company
from . import privacy_purpose
from . import privacy_notice
from . import privacy_notice_version
from . import privacy_consent
from . import privacy_consent_group
from . import privacy_consent_evidence
from . import privacy_contact_preference
from . import privacy_dashboard
from . import privacy_retention
from . import privacy_retention_calendar
from . import privacy_document_classification
from . import privacy_destruction
from . import privacy_destruction_register
from . import privacy_destruction_campaign
from . import privacy_anonymization_assessment
from . import privacy_url_guard
from . import privacy_docuseal_config
from . import privacy_docuseal_interface
from . import privacy_docuseal_template
from . import privacy_libresign_config
from . import privacy_libresign_interface
from . import privacy_libresign_template
from . import privacy_email_sequence
from . import res_partner
from . import project_project
from . import mail_blacklist
