from . import privacy_purpose
from . import privacy_notice
from . import privacy_notice_version
from . import privacy_consent
from . import privacy_consent_group
from . import privacy_consent_evidence
from . import privacy_contact_preference
from . import privacy_dashboard
from . import privacy_retention
from . import privacy_destruction
from . import privacy_docuseal_config
from . import privacy_docuseal_interface
from . import privacy_docuseal_template
from . import privacy_libresign_config
from . import privacy_libresign_interface
from . import privacy_libresign_template
from . import privacy_email_sequence
from . import res_partner
from . import project_project
from . import mail_blacklist
