from . import test_privacy_dashboard
from . import test_privacy_retention
from . import test_privacy_docuseal
from . import test_privacy_portal
from . import test_privacy_email
from . import test_privacy_retention_calendar
from . import test_privacy_document_classification
from . import test_privacy_destruction_register
from . import test_privacy_destruction_campaign
from . import test_privacy_anonymization_assessment
from . import test_privacy_destruction_document_workflow
from . import test_privacy_framework
