{
    "name": "Fox Quest",
    "summary": "Syst\u00e8me de gamification avec XP, niveaux, badges et r\u00e9compenses",
    "version": "18.0.2.3.0",
    "category": "Human Resources",
    'website': 'https://bluefoxconsultant.com',
    "author": "Blue Fox Inc.",
    'license': 'LGPL-3',
    "application": True,
    "installable": True,
    "post_init_hook": "_post_init_backfill",
    "depends": [
        "base",
        "mail",
        "bus",
        "hr_timesheet",
        "project",
        "web",
        "project_knowledge_matrix",
        "hosting_management",
        "helpdesk_mgmt",
        "bf_onboarding_base",
        "bf_meeting",
        "bf_email_management",
    ],
    "data": [
        # Security
        "security/gamification_security.xml",
        "security/ir.model.access.csv",
        # Data
        "data/gamification_level_data.xml",
        "data/gamification_badge_category_data.xml",
        "data/gamification_xp_rule_data.xml",
        "data/gamification_badge_data.xml",
        "data/gamification_cron.xml",
        "data/bf_onboarding.xml",
        # Wizard
        "wizard/grant_badge_wizard_views.xml",
        # Views
        "views/gamification_level_views.xml",
        "views/gamification_badge_category_views.xml",
        "views/gamification_badge_views.xml",
        "views/gamification_user_badge_views.xml",
        "views/gamification_profile_views.xml",
        "views/gamification_reward_views.xml",
        "views/gamification_reward_claim_views.xml",
        "views/gamification_xp_rule_views.xml",
        "views/gamification_xp_transaction_views.xml",
        "views/gamification_dashboard_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_gamification/static/src/scss/gamification.scss",
            "bf_gamification/static/src/scss/achievement_popup.scss",
            "bf_gamification/static/src/scss/levelup_popup.scss",
            "bf_gamification/static/src/js/gamification_bus_service.js",
            "bf_gamification/static/src/js/achievement_popup.js",
            "bf_gamification/static/src/js/levelup_popup.js",
            "bf_gamification/static/src/js/gamification_systray.js",
            "bf_gamification/static/src/js/gamification_dashboard.js",
            "bf_gamification/static/src/xml/achievement_popup.xml",
            "bf_gamification/static/src/xml/levelup_popup.xml",
            "bf_gamification/static/src/xml/gamification_systray.xml",
            "bf_gamification/static/src/xml/gamification_dashboard.xml",
        ],
    },
}
