{
    "name": "SMS & Calls",
    "summary": "Messagerie SMS/MMS live via VOIP.ms + archivage de SMS et journaux d'appels Android",
    "version": "18.0.5.6.0",
    "category": "Tools",
    'author': 'Blue Fox Inc.',
    'website': 'https://bluefoxconsultant.com',
    'license': 'LGPL-3',
    "application": True,
    "installable": True,
    "depends": [
        "base",
        "mail",
        "project",
        "bf_onboarding_base",
    ],
    "external_dependencies": {
        "python": ["defusedxml", "requests", "pywebpush"],
    },
    "post_init_hook": "post_init_hook",
    "data": [
        "security/sms_security.xml",
        "security/ir.model.access.csv",
        "report/sms_paperformat.xml",
        "report/sms_report_templates.xml",
        "wizard/import_wizard_views.xml",
        "wizard/post_to_task_wizard_views.xml",
        "views/sms_thread_views.xml",
        "views/sms_message_views.xml",
        "views/call_views.xml",
        "views/sms_dashboard_views.xml",
        "views/menu_views.xml",
        "views/sms_device_views.xml",
        "views/sms_line_views.xml",
        "views/res_config_settings_views.xml",
        "views/sms_messenger_views.xml",
        # Data
        "data/sms_nc_watch_cron.xml",
        "data/voipms_poll_cron.xml",
        "data/bf_onboarding.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_sms_archive/static/src/js/sms_dashboard.js",
            "bf_sms_archive/static/src/xml/sms_dashboard.xml",
            "bf_sms_archive/static/src/messenger/messenger.js",
            "bf_sms_archive/static/src/messenger/messenger.xml",
            "bf_sms_archive/static/src/messenger/messenger.scss",
            "bf_sms_archive/static/src/systray/sms_systray.js",
            "bf_sms_archive/static/src/systray/sms_systray.xml",
            "bf_sms_archive/static/src/systray/sms_systray.scss",
        ],
    },
}
