from . import bf_email
from . import bf_email_dashboard
from . import bf_email_rule
from . import calendar_alarm_manager
from . import calendar_attendee
from . import mail_message
from . import mail_notification
from . import mail_scheduled_message
from . import res_partner
