{
    "name": "Blue Fox — Helpdesk",
    "summary": "Fork OCA helpdesk_mgmt with BF integrations: hour bank, ticket timesheets, waiting states, branded public form, ntfy critical hook",
    "version": "18.0.4.3.1",
    "category": "After-Sales",
    "author": "Blue Fox Inc.",
    "website": "https://bluefoxconsultant.com",
    'license': 'AGPL-3',
    "depends": [
        "website",
        "helpdesk_mgmt",
        "helpdesk_mgmt_project",
        "hr_timesheet",
        "bf_hour_bank",
        "bf_persona",
        "project_knowledge_matrix",
        "bf_meeting",
        "survey",
        "bf_dashboard",
        "bf_onboarding_base",
        "bf_llm",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/helpdesk_data.xml",
        "data/bf_onboarding.xml",
        "views/helpdesk_menu_views.xml",
        "views/helpdesk_ticket_team_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_macro_views.xml",
        "views/helpdesk_auto_tag_views.xml",
        "views/public_form_templates.xml",
        "views/portal_brand.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "bf_helpdesk/static/src/scss/public_form.scss",
            "bf_helpdesk/static/src/scss/portal_brand.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "application": True,
}
