# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from . import hosting_ntfy
from . import hosting_email_template
from . import hosting_server
from . import hosting_domain
from . import hosting_dmarc_report
from . import hosting_software
from . import hosting_software_version
from . import hosting_service_tag
from . import hosting_accepted_http_code
from . import hosting_service
from . import hosting_service_disconnect_wizard
from . import hosting_update_log
from . import hosting_health_check
from . import hosting_health_daily_snapshot
from . import hosting_maintenance_schedule
from . import hosting_maintenance_template
from . import hosting_dashboard
from . import hosting_digest
from . import res_partner
from . import res_config_settings
from . import hosting_repo_matcher
from . import hosting_backup_repository
from . import hosting_backup_bucket_snapshot
from . import hosting_backup_log
from . import hosting_backup_snapshot
from . import hosting_audit_log
from . import hosting_security_event
from . import hosting_endpoint
from . import hosting_endpoint_group
from . import hosting_license
from . import hosting_license_seat
from . import voipms_connector
from . import hosting_voip_did
from . import hosting_voip_cdr
from . import hosting_voip_transaction
from . import project_project
