from odoo import fields, models

# Letterhead modes, shared by letter.template / letter.document / res.company.
# `banner` and `classic` are generated by QWeb; `image`, `pdf_overlay` and
# `plain` use (or leave room for) the company's own letterhead.
LETTERHEAD_MODES = [
    ("banner", "Bannière foncée (générée)"),
    ("classic", "Classique sobre (générée)"),
    ("image", "Image téléversée (PNG/JPG)"),
    ("pdf_overlay", "PDF téléversé (superposition)"),
    ("plain", "Sans en-tête (papier pré-imprimé)"),
]

# Curated mail-merge token palette. Surfaced as a static legend in the
# template form view; rendering itself accepts any valid expression.
LETTER_MERGE_TOKENS = [
    ("{{ object.partner_id.name }}", "Nom du destinataire"),
    ("{{ object.partner_id.parent_id.name }}", "Organisation du destinataire"),
    ("{{ object.recipient_name }}", "Nom du destinataire (figé sur la lettre)"),
    ("{{ object.letter_date }}", "Date de la lettre"),
    ("{{ object.reference }}", "Référence de la lettre (LET-AAAA-NNN)"),
    ("{{ object.company_id.name }}", "Nom de l'expéditeur"),
    ("{{ object.signatory_id.name }}", "Nom du signataire"),
    ("{{ object.signatory_function }}", "Fonction du signataire"),
]


class LetterTemplate(models.Model):
    _name = "letter.template"
    _description = "Modèle de lettre"
    _order = "name"

    name = fields.Char(string="Nom", required=True)
    active = fields.Boolean(default=True)
    subject = fields.Char(
        string="Objet",
        help="Titre par défaut de la lettre. Peut contenir des champs de fusion.",
    )
    body_html = fields.Html(
        string="Corps",
        sanitize=False,
        help="Corps du modèle. Champs de fusion : {{ object.champ }} ou QWeb "
        "<t t-out=\"object.champ\"/>.",
    )
    letterhead_style = fields.Selection(
        LETTERHEAD_MODES,
        string="En-tête",
        default="banner",
        required=True,
    )
    note = fields.Text(string="Description interne")
    quicktext_ids = fields.Many2many(
        "letter.quicktext",
        string="Blocs de texte suggérés",
    )
