{
    "name": "Gestion des courriels",
    "summary": "Inbox unifiée IMAP + chatters Odoo, avec re-routage UI",
    "version": "18.0.6.7.2",
    "category": "Productivity",
    'website': 'https://bluefoxconsultant.com',
    "author": "Blue Fox Inc.",
    'license': 'LGPL-3',
    "application": True,
    "installable": True,
    "depends": [
        "base",
        "mail",
        "mail_composer_cc_bcc",
        
        "calendar",
        "project",
        "account",
        "bf_onboarding_base",
    ],
    "data": [
        "security/email_security.xml",
        "security/ir.model.access.csv",
        "data/ir_config_parameter.xml",
        "data/email_sync_cron.xml",
        "data/email_sync_imap_cron.xml",
        "data/imap_mirror_cron.xml",
        "data/imap_reconcile_cron.xml",
        "data/expected_reply_minutes_cron.xml",
        "data/auto_link_orphans_cron.xml",
        "data/bf_email_rule_default.xml",
        "data/calendar_reminder_cron.xml",
        "data/bf_onboarding.xml",
        "wizard/bf_email_initial_sync_views.xml",
        "wizard/bf_email_reroute_views.xml",
        "wizard/bf_email_imap_backfill_views.xml",
        "wizard/bf_email_snooze_views.xml",
        "wizard/bf_email_browser_views.xml",
        "wizard/bf_email_guess_route_views.xml",
        "views/bf_email_account_views.xml",
        "views/bf_email_views.xml",
        "views/bf_email_rule_views.xml",
        "views/bf_email_dashboard_views.xml",
        "views/mail_scheduled_message_views.xml",
        "views/res_config_settings_views.xml",
        "views/bf_email_menu.xml",
        "views/res_partner_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_email_management/static/src/js/bf_email_dashboard.js",
            "bf_email_management/static/src/js/bf_email_chatter_action.js",
            "bf_email_management/static/src/js/bf_email_preview_list.js",
            "bf_email_management/static/src/xml/bf_email_preview_list.xml",
            "bf_email_management/static/src/js/bf_calendar_reminder.js",
            "bf_email_management/static/src/js/bf_email_browser.js",
            "bf_email_management/static/src/js/bf_email_new_record_dropdown.js",
            "bf_email_management/static/src/xml/bf_email_dashboard.xml",
            "bf_email_management/static/src/xml/bf_email_browser.xml",
            "bf_email_management/static/src/xml/bf_email_new_record_dropdown.xml",
        ],
    },
}
