{
    "name": "BF Bloc-notes",
    "version": "18.0.2.8.0",
    "category": "Productivity",
    "summary": "Notes rapides riches, multi-liens, conversion en activité, raccourcis et systray",
    'author': 'Blue Fox Inc.',
    "website": "https://bluefoxconsultant.com",
    'license': 'LGPL-3',
    "depends": ["web", "mail", "project", "crm", "contacts", "bf_onboarding_base"],
    "data": [
        "security/ir.model.access.csv",
        "security/bf_note_security.xml",
        "data/bf_note_tag_data.xml",
        "data/bf_onboarding.xml",
        "views/bf_note_views.xml",
        "views/bf_note_tag_views.xml",
        "views/bf_note_activity_wizard_views.xml",
        "views/bf_note_task_wizard_views.xml",
        "views/bf_note_reroute_views.xml",
        "views/res_users_views.xml",
        "views/bf_note_menus.xml",
        "views/res_partner_views.xml",
        "views/project_task_views.xml",
        "views/crm_lead_views.xml",
        "views/project_project_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bf_bloc_notes/static/src/scss/bf_note.scss",
            "bf_bloc_notes/static/src/js/bf_note_service.js",
            "bf_bloc_notes/static/src/js/bf_note_systray.js",
            "bf_bloc_notes/static/src/js/bf_note_quick_create.js",
            "bf_bloc_notes/static/src/js/bf_note_hotkeys.js",
            "bf_bloc_notes/static/src/xml/bf_note_templates.xml",
        ],
    },
    "installable": True,
    "application": True,
}
