{
    "name": "Blue Fox — Productivity Pack",
    "summary": "UI polish, dashboards, command palette, notes, timer, and brand pack for Odoo CE",
    "version": "18.0.1.0.0",
    "category": "Productivity",
    "license": "LGPL-3",
    "author": "Blue Fox Inc.",
    "website": "https://bluefoxconsultant.com",
    "depends": [
        "bf_universal_search",
        "bf_bloc_notes",
        "bf_bureau",
        "bf_timesheet_timer",
        "bf_time_of_day",
        "bf_task_unblock_notify",
        "daily_todo_digest",
        "bf_lexend",
        "bf_dark_mode",
        "bluefox_branding",
    ],
    "data": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
