from . import meeting_record
from . import meeting_decision
from . import meeting_topic
from . import meeting_agenda
from . import meeting_agenda_topic
from . import meeting_attendance
from . import meeting_dashboard
from . import calendar_event
from . import project_task
from . import project_project
from . import res_partner
from . import res_users
from . import ir_attachment
from . import knowledge_item
from . import onboarding_onboarding
from . import res_company
