from . import gamification_level
from . import gamification_badge_category
from . import gamification_badge
from . import gamification_user_badge
from . import gamification_xp_transaction
from . import gamification_xp_rule
from . import gamification_profile
from . import gamification_reward
from . import gamification_dashboard
from . import res_config_settings
from . import account_analytic_line
from . import project_task
from . import project_document
from . import hosting_maintenance
from . import mail_message
from . import mail_activity
from . import helpdesk_ticket
from . import meeting_record
from . import meeting_agenda
from . import meeting_decision
from . import knowledge_item
from . import corporate_resolution
from . import bf_email
from . import onboarding_onboarding
